/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Storage */

#ifndef _Included_Storage
#define _Included_Storage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Storage
 * Method:    initializeHardwarePorts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_initializeHardwarePorts
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    moveXRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_moveXRight
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    moveXLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_moveXLeft
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    stopX
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_stopX
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    getXPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Storage_getXPos
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    moveZUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_moveZUp
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    moveZDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_moveZDown
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    stopZ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_stopZ
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    getZPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Storage_getZPos
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    moveYInside
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_moveYInside
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    moveYOutside
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_moveYOutside
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    stopY
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_stopY
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    getYPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Storage_getYPos
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    getSwitch1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Storage_getSwitch1
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    getSwitch2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Storage_getSwitch2
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    getSwitch1_2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Storage_getSwitch1_12
  (JNIEnv *, jclass);

/*
 * Class:     Storage
 * Method:    ledOn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Storage_ledOn
  (JNIEnv *, jclass, jint);

/*
 * Class:     Storage
 * Method:    ledsOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Storage_ledsOff
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
